### ISSUE TITLE
NEW LOOK

### ISSUE THREAD

**Issue by as280093** [HANDZCZ/genshin-stats#1]
Try this if looks good
<table>
<tr><th>Mondstadt </th><th>Dragonspine</th><th>Liyue</th></tr>
<tr><td>

|Stat|Value|
|-|-|
Explored | 97.7%
Reputation level | 8

</td><td>

|Stat|Value|
|-|-|
Explored | 100.0%
Offering level | 12

</td><td>

|Stat|Value|
|-|-|
Explored | 96.2%
Reputation level | 8

</td></tr> 
</table>

**Comment by as280093** [comment]
```
<table>
<tr><th>Mondstadt </th><th>Dragonspine</th><th>Liyue</th></tr>
<tr><td>

|Stat|Value|
|-|-|
Explored | 97.7%
Reputation level | 8

</td><td>

|Stat|Value|
|-|-|
Explored | 100.0%
Offering level | 12

</td><td>

|Stat|Value|
|-|-|
Explored | 96.2%
Reputation level | 8

</td></tr> 
</table>
```

**Comment by HANDZCZ** [comment]
I like your design it looks great. I tried to improve it with css, but css doesn't work in github markdown 😐. The new design has only one flaw. It's totally broken in github mobile app.

**Comment by as280093** [comment]
css doesnt work only Markdown and common HTML
