### ISSUE TITLE
is it possible to run on other platform

### ISSUE THREAD

**Issue by WSrujan** [HANDZCZ/genshin-stats#12]
look like github has banned this repo
my alt acc getting banned when i fork this repo and run

**Comment by HANDZCZ** [comment]
That's weird never heard of this happening. I didn't get any email from Github about my repo. I looked into their TOS on actions, and I am not violating any, so there shouldn't be any problem with my repo.
Also when I was searching your problem I came across [this](https://docs.github.com/en/github/site-policy/github-terms-of-service#3-account-requirements).

>3. Account Requirements
>We have a few simple rules for User Accounts on GitHub's Service.
>
> - **One person or legal entity may maintain no more than one free Account (if you choose to control a machine account as well, that's fine, but it can only be used for running a machine).**

**Comment by WSrujan** [comment]
is there any restriction on brand new github acc?

**Comment by WSrujan** [comment]
also how to fix this 
![image](https://user-images.githubusercontent.com/49693115/149182234-f5b9acc9-7fa5-4dd9-89e9-96c32916e112.png)

**Comment by HANDZCZ** [comment]
There is a check for how many battles you have done in abys. That should have stopped this from happening, but for some reason, you have more than 0 battles and you don't have any strongest hit?
Maybe you entered abys and left without fighting, that would explain this, but I need to test this...

**Comment by WSrujan** [comment]
i did fight abys reached 2-3

**Comment by WSrujan** [comment]
Now its fixed
