### ISSUE TITLE
Optimize background-image for the mobile version

### ISSUE THREAD

**Issue by Yashirow** [HANDZCZ/genshin-stats#12]
Background image isn't optimized for the mobile version unlike characters images turning into icons. Maybe adding some media queries could be a good fix ? Or disabling bg image when in phone mode.

**Comment by HANDZCZ** [comment]
Changed the background behavior (a6181d3617ad44a4196117e40d892e22775b4aa8). 
Screens with less than 1200px width will show black background instead of an image.

**Comment by Yashirow** [comment]
Nice, thanks.

**Comment by Yashirow** [comment]
Off topic but fyi genshin.py now support dendroculi count.
`<tr><td>Dendroculi</td><td>${user.stats.dendroculi}</td></tr>`

**Comment by HANDZCZ** [comment]
Oh ok, I will add it then.
I haven't played genshin for at least a few months so I have no idea what's new.

**Comment by Yashirow** [comment]
Well a new region so new oculus, new chara ect..
