### ISSUE TITLE
how to use this? 

### ISSUE THREAD

**Issue by tehrzky** [HANDZCZ/genshin-stats#14]
tnx

**Comment by HANDZCZ** [comment]
Have a look at the [wiki - page setup](https://github.com/HANDZCZ/genshin-stats/wiki/Setup)

Duplicate of #5

**Comment by tehrzky** [comment]
tnx, i think its working now. and last do i really need to update authkey every 24 hrs?

**Comment by HANDZCZ** [comment]
Yes if you want it to show you the current primogem count, but updating it once a month is fine.
The primogem log shows only the last 3 months history, so if you update it in time it will show the right amount.
If you update it after the 3 months it will get "desynced."

**Comment by tehrzky** [comment]
i see.. tnx again.
