### ISSUE TITLE
Does this support multiple region

### ISSUE THREAD

**Issue by WSrujan** [HANDZCZ/genshin-stats#16]
I play on Asia and North America servers will it redemption code on both? Daily login? 
Or do have to make separate repo for it?

**Comment by HANDZCZ** [comment]
The functions take ``chinese`` as an argument so you would need 2 repos. One for NA and another for Asia where you would need to set the ``chinese`` to true to all the functions that need it.

**Comment by WSrujan** [comment]
Okay got it
