### ISSUE TITLE
Run main.py problem

### ISSUE THREAD

**Issue by tmlong240402** [HANDZCZ/genshin-stats#18]
![image](https://user-images.githubusercontent.com/105640517/175208935-1a192828-828e-4dc7-b8b3-5f2a166ce6c2.png)
i have this error when run work
please help me

**Comment by HANDZCZ** [comment]
You have probably set `DAILY_OR_ERR` to something, and it crashed because daily was already claimed.

**Comment by tmlong240402** [comment]
@HANDZCZ 
![image](https://user-images.githubusercontent.com/105640517/175484198-44ac8f29-b339-4e0a-b7fd-3a896b31e05c.png)
![image](https://user-images.githubusercontent.com/105640517/175484341-17ed9642-3339-4f78-a5f2-55792d1b7fe0.png)
![image](https://user-images.githubusercontent.com/105640517/175484387-c5537e23-ac7a-4b8a-9f54-eddf9b5131c1.png)
![image](https://user-images.githubusercontent.com/105640517/175484548-c89dcb07-45c1-48ae-af33-34757199a646.png)



i alreadt run a check and re enter cookie, ingame uid but it alway say error
but the fact is i done get the reward daily

**Comment by HANDZCZ** [comment]
The daily or error works as intended. You have a different problem.
![image](https://user-images.githubusercontent.com/35496843/175503432-22151d8e-672e-4383-a9e1-2ee7cfa77a9e.png)
You need to enable everything related to genshin [here](https://www.hoyolab.com/setting/privacy).
![image](https://user-images.githubusercontent.com/35496843/175502985-3d67d2c5-530b-4446-871e-880be6a9a1b9.png)

**Comment by tmlong240402** [comment]
i see
i run a check again with your update
but the problem now is if the workflow error, did the code still check giftcode and redeems it

**Comment by tmlong240402** [comment]
![image](https://user-images.githubusercontent.com/105640517/175758128-261cc078-f7a7-442f-a1dc-8bdcee9e879f.png)
turn on all but still have error 
![image](https://user-images.githubusercontent.com/105640517/175758140-64f438bd-5c76-4d6f-943a-482b32f36cf5.png)

**Comment by HANDZCZ** [comment]
If you have enabled ``DAILY_OR_ERR`` and it fails it doesn't get to the code redeem.
Also if ``DAILY_OR_ERR`` is enabled it can run only once a day without fail.
You probably ran it before reset and it failed. Just let it run on schedule and see if it fails, or delete the ``DAILY_OR_ERR`` secret.

**Comment by tmlong240402** [comment]
i see
i will try it in tomorrow
