### ISSUE TITLE
[Feature Request] HoYoLAB Community Genshin Impact daily check-in

### ISSUE THREAD

**Issue by as280093** [HANDZCZ/genshin-stats#2]
Same as Daily Login for Genshin HoYoLaB's Community FOrum Gives +5 xp on Daily Login also it has been implemented Here
https://github.com/y1ndan/genshinhelper

**Comment by HANDZCZ** [comment]
I intentionally didn't implement it. I am using [genshin-daily](https://github.com/rabelloo/genshin-daily). The python library [genshinstats](https://github.com/thesadru/genshinstats), can't do the first sing-in. I don't know that for sure and the documentation doesn't mention anything either. I just found [this in code "First sign-in must be done manually. Please go to the website and claim your rewards."](https://github.com/thesadru/genshinstats/blob/master/genshinstats/signin.py#L44).
