### ISSUE TITLE
is there any alternative to heroku?

### ISSUE THREAD

**Issue by tehrzky** [HANDZCZ/genshin-stats#2]
i cant use it because it needs credit card to verify account. im stuck on step 8) , iv. 
tnx

and im southeast asia user.

**Comment by HANDZCZ** [comment]
I edited the guide and added code to get around the addon thing.
Try following the guide now. You shouldn't encounter any more problems.

PS: Numbering changed so you should be at step ``7) iv.``. Also, don't forget to update your fork.

**Comment by tehrzky** [comment]
@HANDZCZ tnx for updating. 👍👍👍
