### ISSUE TITLE
should i paste the whole cookies on GAME_UID

### ISSUE THREAD

**Issue by tehrzky** [HANDZCZ/genshin-stats#4]
mi18nLang=en-us; _MHYUUID=xxx; ltoken=xxx; ltuid=xxx; G_ENABLED_IDPS=google; DEVICEFP_SEED_ID=xxx; DEVICEFP_SEED_TIME=xxx; DEVICEFP=xxx; G_AUTHUSER_H=0

this one? ty

**Comment by HANDZCZ** [comment]
The config vars on Heroku should look something like this:

|Key|Value|
|-|-|
GAME_UID | your UID in genshin impact game (eg. 746745754)
COOKIE | cookie you copy from hoyolab (eg. _MHYUUID=xxx; ltoken=xxx; ltuid=xxx; ...)
WEB_KEY | some key you generated (must be the same in index.php and config vars) (eg. dauhbdahikjdhnkajjdkaskskndv)
WEB_URL | URL of the website where you uploaded index.php (eg. https://genshin.handz.us.to/)

---

GAME_UID contains your UID in-game. You obtain it by going to the profile tab and clicking copy.

![image](https://user-images.githubusercontent.com/35496843/179950744-2d23bf24-423b-43ff-9465-126c49896f39.png)

**Comment by tehrzky** [comment]
ok got it, but my heroku app says
https://genshinstat.herokuapp.com/

 "Not yet"

**Comment by HANDZCZ** [comment]
I assume you didn't run it between ``16:10 UTC`` and ``16:40 UTC``. That's the only time the app updates your stats.
Its setup that it will run a few minutes after reset and only once a day.
