### ISSUE TITLE
Which host site do you recommend for uploading index.php ?

### ISSUE THREAD

**Issue by Yashirow** [HANDZCZ/genshin-stats#5]
I'm not really familiar with hosting website other than mega/mediafire ect sorry

**Comment by HANDZCZ** [comment]
I am using https://byet.host for now, but you can use whatever you want.
If you will use byet.host, then sign up with your Gmail account otherwise they will disable it (something about disposable email addresses and abuse from unknown email providers).
I found [this tutorial](https://www.youtube.com/watch?v=U2kDB_8B9-s) on creating the website and uploading files. Interfaces might look a little different, but the steps are almost the same. The only difference is you first delete everything in the folder htdocs.
After you upload index.php it should look like this (without the page.html):
![image](https://user-images.githubusercontent.com/35496843/180568706-690f70a2-e08b-4545-b590-b9e11aaaec1f.png)

**Comment by Yashirow** [comment]
Okay thanks. The custom domain name that you use is a premium feature, right ?

**Comment by HANDZCZ** [comment]
Nope, I only added an addon domain.
You must have an access to a domain name though (specifically NS records).

**Comment by Yashirow** [comment]
Can I ask you how to do this ?

**Comment by HANDZCZ** [comment]
1. You will need to buy or somehow get yourself a domain name. The domain registrar must support NS records.
2. You set the NS records to byet.host name servers.
    Optionally you can create a subdomain and set its NS records to byet.host name servers instead of the domain you obtained.
    (eg. the domain that I got is ``handz.us.to`` and I created a genshin subdomain (``genshin.handz.us.to``) and set its NS records to byet.host name servers)
3. Wait for propagation.
4. When you click Add domain it should succeed. If not you must wait longer.
5. All done now you have a new folder named after your domain, where you upload your files instead.

**Comment by Yashirow** [comment]
Okay thanks. By the way I got an error in heroku after the last deploy and my byet webpage is still blank.. Heroku says "read the log for errors" but there's no errors in the log. I readed a second time all the steps but I don't see any differences. Do you know what can cause this ?

**Comment by HANDZCZ** [comment]
If you mean this:
![image](https://user-images.githubusercontent.com/35496843/180608675-7f40247e-5332-4a0d-8ab6-062de77b92af.png)
Then it's working as it should. It will run automatically at 16:30 UTC so in about 2 hours and 10 minutes.
Or you can run it manually by going to ``More -> Run console``, typing ``python3 main.py`` and hitting enter.

**Comment by HANDZCZ** [comment]
The app will be mostly off, only starting once a day for a few seconds.
It's done this way to not consume your dyno hours.
My app used 0.81 hours this month so you can run about 1000 of these...

**Comment by Yashirow** [comment]
Oh yes sorry I'm dumb. Anyway thanks for the app !

**Comment by Yashirow** [comment]
Okay so it claims well the rewards but the website is still blank, did I miss smth in the byet control pannel ?

**Comment by HANDZCZ** [comment]
Umm for some reason they added a check for bots on post requests.
So this hosting will sadly not work for you. It's working for me because I am using Cloudflare which it somehow trusts.

**Comment by Yashirow** [comment]
Okay thanks, at least it claims the rewards. I'll search for another host another day.

**Comment by HANDZCZ** [comment]
So I found a working web hosting but it's a downgrade. No SSL and only 5GB of bandwidth.
But it's without that annoying antibot bs that is useless anyways.
https://www.awardspace.com/free-hosting/

1. When it redirects you close all popups it throws at you.
1. Click on ``Domain manager``
    ![image](https://user-images.githubusercontent.com/35496843/180621216-4bd72b7a-7c03-475a-9bcc-edbe7f5deb46.png)
1. Click on ``Create a Free Subdomain``
    1. Chose a name and click create
1. After that you should see something like this:
   ![image](https://user-images.githubusercontent.com/35496843/180621327-8b165093-e630-49e2-8802-5dfeda9d2729.png)
1. Click ``open files`` and upload index.php
1. Update WEB_URL on Heroku and update URL on Github

After all this, it should work.

**Comment by Yashirow** [comment]
Thanks I'll give it a try
