### ISSUE TITLE
Warning shows when displaying the php page. Blank page even after deploy. 

### ISSUE THREAD

**Issue by rairulyle** [HANDZCZ/genshin-stats#8]
Hi, 

I am using awardspace as my hosting service (as you have suggested) but it showing an error
![image](https://user-images.githubusercontent.com/12708526/182220029-7b3a8460-f855-4b89-b5a9-2a60971e36d2.png)

Great rework btw!

**Comment by HANDZCZ** [comment]
Oops forgot to update the readme.
This should/could happen since you don't have page.html yet.

Also, it's only a warning...
<img src="https://pbs.twimg.com/media/EEVShVXUUAU5JS3.jpg" width=400>

**Comment by rairulyle** [comment]
@HANDZCZ 
Ahhh sorry... Yeah it is a warning hahaha! 

I also tried to deploy the Heroku manually but it still display a blank page. I was expecting to have a working page now.

**Comment by rairulyle** [comment]
@HANDZCZ ,

It still doesn't work but the job has been triggered. There was an error in the python bot when I checked the logs:

![image](https://user-images.githubusercontent.com/12708526/182555333-5e26e7aa-7303-4991-9716-ee824180b8b6.png)

**Comment by HANDZCZ** [comment]
Looks like this is a [problem with the genshin.py lib](https://github.com/thesadru/genshin.py/issues/45).
All you can do now is wait for a new release to fix it.

**Comment by rairulyle** [comment]
Is there a way to have an option to get just the auto-check in and get codes till the above issue is fixed? The HTML is actually just good to have for me.

**Comment by HANDZCZ** [comment]
I reorganized the code to first claim the daily reward and new codes. After that, it gets user data for template filling.

**Comment by rairulyle** [comment]
@HANDZCZ , saw the code! Thanks for this. Will pull.

**Comment by rairulyle** [comment]
Closing this issue as the problem is related to lib.
