### ISSUE TITLE
Bug action error

### ISSUE THREAD

**Issue by WSrujan** [HANDZCZ/genshin-stats#9]
![image](https://user-images.githubusercontent.com/49693115/147884801-4455be28-f0b9-4e90-9a8d-622050e0a7a6.png)
tried to re enter env many time still its failing

**Comment by HANDZCZ** [comment]
You have an extra newline at the end of the file.

![image](https://user-images.githubusercontent.com/35496843/147886574-77d2c50c-4fb6-4bce-bf25-17f34d2a2af2.png)

**Comment by WSrujan** [comment]
![image](https://user-images.githubusercontent.com/49693115/147887723-04bbed85-2d22-4090-a706-513cc7742ed7.png)
its two lines

**Comment by HANDZCZ** [comment]
Github probably isn't showing it, but if you download the file and view the hidden symbols, you can see the new line at the end of the file.

```bash
┌─« ~
└─» curl https://raw.githubusercontent.com/WSrujan/genshin-stats/main/primos.txt 2> /dev/null | cat -A
2022-01-02 14:07:13$
413$

┌─« ~
└─» curl https://raw.githubusercontent.com/HANDZCZ/genshin-stats/main/primos.txt 2> /dev/null | cat -A
2022-01-01 16:59:26$
10337
┌─« ~
└─»
```

>Usage: /bin/cat [OPTION]... [FILE]...
>Concatenate FILE(s) to standard output.
>
>With no FILE, or when FILE is -, read standard input.
>
>  -A, --show-all           equivalent to -vET
>  -E, --show-ends          display $ at end of each line
>  -T, --show-tabs          display TAB characters as ^I
>  -v, --show-nonprinting   use ^ and M- notation, except for LFD and TAB

**Comment by WSrujan** [comment]
fixed
GitHub hid last empty line  (even after deleting and making new one) so i upload it instead
